import { Exchange } from '@packages/types';

const BINANCE_KEYS = {
  API_SECRET: 'binance_api_secret',
  API_KEY: 'binance_api_key',
};

const BINANCE_TESTNET_KEYS = {
  API_SECRET: 'binance-testnet_api_secret',
  API_KEY: 'binance-testnet_api_key',
};

const BINANCE_USDM_KEYS = {
  API_SECRET: 'binance-usdm_api_secret',
  API_KEY: 'binance-usdm_api_key',
};

const OKX_KEYS = {
  API_SECRET: 'okx_api_secret',
  API_KEY: 'okx_api_key',
  PASSWORD: 'okx_password',
};

const GATE_IO_KEYS = {
  API_SECRET: 'gateio_api_secret',
  API_KEY: 'gateio_api_key',
  USER_ID: 'gateio_user_id',
};

const BYBIT_KEYS = {
  API_SECRET: 'bybit_api_secret',
  API_KEY: 'bybit_api_key',
};

const BINANCE = {
  code: 'binance',
  name: 'Binance',
  disabled: false,
  sandbox: false,
  fields: [
    {
      name: BINANCE_KEYS.API_KEY,
      type: 'string' as const,
      label: 'API Key',
    },
    {
      name: BINANCE_KEYS.API_SECRET,
      type: 'string' as const,
      label: 'API Secret',
    },
  ],
};

const BINANCE_USDM = {
  code: 'binanceusdm',
  name: 'Binance (Futures)',
  disabled: false,
  sandbox: false,
  fields: [
    {
      name: BINANCE_USDM_KEYS.API_KEY,
      type: 'string' as const,
      label: 'API Key',
    },
    {
      name: BINANCE_USDM_KEYS.API_SECRET,
      type: 'string' as const,
      label: 'API Secret',
    },
  ],
};

const BINANCE_US = {
  code: 'binanceus',
  name: 'Binance US',
  disabled: false,
  sandbox: false,
  fields: [
    {
      name: BINANCE_USDM_KEYS.API_KEY,
      type: 'string' as const,
      label: 'API Key',
    },
    {
      name: BINANCE_USDM_KEYS.API_SECRET,
      type: 'string' as const,
      label: 'API Secret',
    },
  ],
};

const BINANCE_TESTNET = {
  code: 'binanceusdm-testnet',
  name: 'Binance Testnet',
  disabled: false,
  sandbox: true,
  fields: [
    {
      name: BINANCE_TESTNET_KEYS.API_KEY,
      type: 'string' as const,
      label: 'API Key',
    },
    {
      name: BINANCE_TESTNET_KEYS.API_SECRET,
      type: 'string' as const,
      label: 'API Secret',
    },
  ],
};

const OKX = {
  code: 'okx',
  name: 'OKX (Futures)',
  disabled: false,
  sandbox: false,
  fields: [
    {
      name: OKX_KEYS.API_KEY,
      type: 'string' as const,
      label: 'API Key',
    },
    {
      name: OKX_KEYS.API_SECRET,
      type: 'string' as const,
      label: 'API Secret',
    },
    {
      name: OKX_KEYS.PASSWORD,
      type: 'string' as const,
      label: 'Password',
    },
  ],
};

const GATE_IO = {
  code: 'gateio',
  name: 'Gate.io (Futures)',
  disabled: false,
  sandbox: false,
  fields: [
    {
      name: GATE_IO_KEYS.API_KEY,
      type: 'string' as const,
      label: 'API Key',
    },
    {
      name: GATE_IO_KEYS.API_SECRET,
      type: 'string' as const,
      label: 'API Secret',
    },
    {
      name: GATE_IO_KEYS.USER_ID,
      type: 'string' as const,
      label: 'User ID',
    },
  ],
};

const GATE_IO_MOCK = {
  code: 'gateio-mock',
  name: 'Gate.io Mock (Futures)',
  disabled: false,
  sandbox: false,
  fields: [],
};

const BYBIT = {
  code: 'bybit',
  name: 'Bybit (Futures)',
  disabled: false,
  sandbox: false,
  fields: [
    {
      name: BYBIT_KEYS.API_KEY,
      type: 'string' as const,
      label: 'API Key',
    },
    {
      name: BYBIT_KEYS.API_SECRET,
      type: 'string' as const,
      label: 'API Secret',
    },
  ],
};

export const EXCHANGE_KEYS = {
  BINANCE: BINANCE_KEYS,
  BINANCE_TESTNET: BINANCE_TESTNET_KEYS,
  BINANCE_USDM: BINANCE_USDM_KEYS,
  OKX: OKX_KEYS,
  GATE_IO: GATE_IO_KEYS,
  GATE_IO_MOCK: undefined,
  BYBIT: BYBIT_KEYS,
};

export const EXCHANGE_LIST: Exchange[] = [
  BINANCE_TESTNET,
  /* BINANCE,*/ BINANCE_USDM,
  BINANCE_US,
  OKX,
  GATE_IO,
  GATE_IO_MOCK,
  BYBIT,
];

export const BINANCE_USDM_HARDCODED_LEVERAGES = {
  'BTC/USDT:USDT': 125,
  'ETH/USDT:USDT': 125,
  'BCH/USDT:USDT': 75,
  'XRP/USDT:USDT': 75,
  'EOS/USDT:USDT': 75,
  'LTC/USDT:USDT': 75,
  'TRX/USDT:USDT': 75,
  'ETC/USDT:USDT': 75,
  'LINK/USDT:USDT': 75,
  'XLM/USDT:USDT': 50,
  'ADA/USDT:USDT': 75,
  'XMR/USDT:USDT': 50,
  'DASH/USDT:USDT': 50,
  'ZEC/USDT:USDT': 50,
  'XTZ/USDT:USDT': 50,
  'BNB/USDT:USDT': 75,
  'ATOM/USDT:USDT': 75,
  'ONT/USDT:USDT': 50,
  'IOTA/USDT:USDT': 50,
  'BAT/USDT:USDT': 50,
  'VET/USDT:USDT': 50,
  'NEO/USDT:USDT': 50,
  'QTUM/USDT:USDT': 50,
  'IOST/USDT:USDT': 50,
  'THETA/USDT:USDT': 50,
  'ALGO/USDT:USDT': 50,
  'ZIL/USDT:USDT': 50,
  'KNC/USDT:USDT': 50,
  'ZRX/USDT:USDT': 50,
  'COMP/USDT:USDT': 25,
  'OMG/USDT:USDT': 50,
  'DOGE/USDT:USDT': 75,
  'SXP/USDT:USDT': 25,
  'KAVA/USDT:USDT': 25,
  'BAND/USDT:USDT': 50,
  'RLC/USDT:USDT': 25,
  'WAVES/USDT:USDT': 50,
  'MKR/USDT:USDT': 50,
  'SNX/USDT:USDT': 50,
  'DOT/USDT:USDT': 75,
  'DEFI/USDT:USDT': 20,
  'YFI/USDT:USDT': 50,
  'BAL/USDT:USDT': 25,
  'CRV/USDT:USDT': 25,
  'TRB/USDT:USDT': 50,
  'RUNE/USDT:USDT': 50,
  'SUSHI/USDT:USDT': 50,
  'EGLD/USDT:USDT': 25,
  'SOL/USDT:USDT': 100,
  'ICX/USDT:USDT': 20,
  'STORJ/USDT:USDT': 21,
  'BLZ/USDT:USDT': 20,
  'UNI/USDT:USDT': 75,
  'AVAX/USDT:USDT': 75,
  'FTM/USDT:USDT': 50,
  'ENJ/USDT:USDT': 25,
  'FLM/USDT:USDT': 50,
  'REN/USDT:USDT': 50,
  'KSM/USDT:USDT': 50,
  'NEAR/USDT:USDT': 50,
  'AAVE/USDT:USDT': 50,
  'FIL/USDT:USDT': 75,
  'RSR/USDT:USDT': 25,
  'LRC/USDT:USDT': 50,
  'MATIC/USDT:USDT': 75,
  'OCEAN/USDT:USDT': 25,
  'BEL/USDT:USDT': 20,
  'CTK/USDT:USDT': 11,
  'AXS/USDT:USDT': 50,
  'ALPHA/USDT:USDT': 50,
  'ZEN/USDT:USDT': 50,
  'SKL/USDT:USDT': 20,
  'GRT/USDT:USDT': 50,
  '1INCH/USDT:USDT': 25,
  'CHZ/USDT:USDT': 50,
  'SAND/USDT:USDT': 50,
  'ANKR/USDT:USDT': 25,
  'LIT/USDT:USDT': 20,
  'UNFI/USDT:USDT': 20,
  'REEF/USDT:USDT': 20,
  'RVN/USDT:USDT': 50,
  'SFP/USDT:USDT': 25,
  'XEM/USDT:USDT': 25,
  'COTI/USDT:USDT': 25,
  'CHR/USDT:USDT': 25,
  'MANA/USDT:USDT': 50,
  'ALICE/USDT:USDT': 20,
  'HBAR/USDT:USDT': 50,
  'ONE/USDT:USDT': 20,
  'LINA/USDT:USDT': 20,
  'STMX/USDT:USDT': 20,
  'DENT/USDT:USDT': 25,
  'CELR/USDT:USDT': 25,
  'HOT/USDT:USDT': 25,
  'MTL/USDT:USDT': 25,
  'OGN/USDT:USDT': 20,
  'NKN/USDT:USDT': 20,
  'DGB/USDT:USDT': 11,
  '1000SHIB/USDT:USDT': 50,
  'BAKE/USDT:USDT': 50,
  'GTC/USDT:USDT': 20,
  'BTCDOM/USDT:USDT': 20,
  'IOTX/USDT:USDT': 20,
  'AUDIO/USDT:USDT': 20,
  'C98/USDT:USDT': 25,
  'MASK/USDT:USDT': 50,
  'ATA/USDT:USDT': 20,
  'DYDX/USDT:USDT': 50,
  '1000XEC/USDT:USDT': 20,
  'GALA/USDT:USDT': 50,
  'CELO/USDT:USDT': 50,
  'AR/USDT:USDT': 50,
  'KLAY/USDT:USDT': 50,
  'ARPA/USDT:USDT': 20,
  'CTSI/USDT:USDT': 25,
  'LPT/USDT:USDT': 50,
  'ENS/USDT:USDT': 50,
  'PEOPLE/USDT:USDT': 50,
  'ANT/USDT:USDT': 21,
  'ROSE/USDT:USDT': 25,
  'DUSK/USDT:USDT': 25,
  'FLOW/USDT:USDT': 20,
  'IMX/USDT:USDT': 50,
  'API3/USDT:USDT': 50,
  'GMT/USDT:USDT': 50,
  'APE/USDT:USDT': 50,
  'WOO/USDT:USDT': 50,
  'JASMY/USDT:USDT': 50,
  'DAR/USDT:USDT': 25,
  'GAL/USDT:USDT': 20,
  'OP/USDT:USDT': 50,
  'INJ/USDT:USDT': 25,
  'STG/USDT:USDT': 25,
  'SPELL/USDT:USDT': 20,
  '1000LUNC/USDT:USDT': 50,
  'LUNA2/USDT:USDT': 20,
  'LDO/USDT:USDT': 50,
  'CVX/USDT:USDT': 20,
  'ICP/USDT:USDT': 25,
  'APT/USDT:USDT': 50,
  'QNT/USDT:USDT': 20,
  'FET/USDT:USDT': 25,
  'FXS/USDT:USDT': 20,
  'HOOK/USDT:USDT': 20,
  'MAGIC/USDT:USDT': 20,
  'T/USDT:USDT': 20,
  'RNDR/USDT:USDT': 20,
  'HIGH/USDT:USDT': 25,
  'MINA/USDT:USDT': 50,
  'ASTR/USDT:USDT': 20,
  'AGIX/USDT:USDT': 25,
  'PHB/USDT:USDT': 20,
  'GMX/USDT:USDT': 25,
  'CFX/USDT:USDT': 50,
  'STX/USDT:USDT': 25,
  'BNX/USDT:USDT': 20,
  'ACH/USDT:USDT': 20,
  'SSV/USDT:USDT': 20,
  'CKB/USDT:USDT': 20,
  'PERP/USDT:USDT': 50,
  'TRU/USDT:USDT': 20,
  'LQTY/USDT:USDT': 20,
  'USDC/USDT:USDT': 50,
  'ID/USDT:USDT': 20,
  'ARB/USDT:USDT': 50,
  'JOE/USDT:USDT': 20,
  'TLM/USDT:USDT': 20,
  'AMB/USDT:USDT': 20,
  'LEVER/USDT:USDT': 20,
  'RDNT/USDT:USDT': 50,
  'HFT/USDT:USDT': 20,
  'XVS/USDT:USDT': 20,
  'ETH/BTC:BTC': 100,
  'BLUR/USDT:USDT': 50,
  'EDU/USDT:USDT': 50,
  'IDEX/USDT:USDT': 20,
  'SUI/USDT:USDT': 50,
  '1000PEPE/USDT:USDT': 50,
  '1000FLOKI/USDT:USDT': 20,
  'UMA/USDT:USDT': 50,
  'RAD/USDT:USDT': 20,
  'KEY/USDT:USDT': 20,
  'COMBO/USDT:USDT': 20,
  'NMR/USDT:USDT': 20,
  'MAV/USDT:USDT': 20,
  'MDT/USDT:USDT': 20,
  'XVG/USDT:USDT': 20,
  'WLD/USDT:USDT': 75,
  'PENDLE/USDT:USDT': 20,
  'ARKM/USDT:USDT': 20,
  'AGLD/USDT:USDT': 50,
  'YGG/USDT:USDT': 50,
  'DODOX/USDT:USDT': 20,
  'BNT/USDT:USDT': 50,
  'OXT/USDT:USDT': 20,
  'SEI/USDT:USDT': 50,
  'CYBER/USDT:USDT': 20,
  'HIFI/USDT:USDT': 50,
  'ARK/USDT:USDT': 20,
  'FRONT/USDT:USDT': 50,
  'GLMR/USDT:USDT': 20,
  'BICO/USDT:USDT': 20,
  'LOOM/USDT:USDT': 20,
  'BIGTIME/USDT:USDT': 50,
  'BOND/USDT:USDT': 50,
  'ORBS/USDT:USDT': 50,
  'STPT/USDT:USDT': 50,
  'WAXP/USDT:USDT': 50,
  'BSV/USDT:USDT': 50,
  'RIF/USDT:USDT': 50,
  'POLYX/USDT:USDT': 50,
  'GAS/USDT:USDT': 50,
  'POWR/USDT:USDT': 50,
  'SLP/USDT:USDT': 50,
  'TIA/USDT:USDT': 50,
  'SNT/USDT:USDT': 50,
  'CAKE/USDT:USDT': 50,
  'MEME/USDT:USDT': 50,
  'TWT/USDT:USDT': 50,
  'TOKEN/USDT:USDT': 50,
  'ORDI/USDT:USDT': 75,
  'STEEM/USDT:USDT': 50,
  'BADGER/USDT:USDT': 50,
  'ILV/USDT:USDT': 50,
  'NTRN/USDT:USDT': 50,
  'MBL/USDT:USDT': 50,
  'KAS/USDT:USDT': 50,
  'BEAMX/USDT:USDT': 50,
  '1000BONK/USDT:USDT': 50,
  'PYTH/USDT:USDT': 50,
  'SUPER/USDT:USDT': 50,
  'USTC/USDT:USDT': 50,
  'ONG/USDT:USDT': 50,
  'ETHW/USDT:USDT': 50,
  'JTO/USDT:USDT': 50,
  '1000SATS/USDT:USDT': 50,
  'AUCTION/USDT:USDT': 50,
  '1000RATS/USDT:USDT': 50,
  'ACE/USDT:USDT': 50,
  'MOVR/USDT:USDT': 50,
  'NFP/USDT:USDT': 50,
  'BTC/USDC:USDC': 125,
  'ETH/USDC:USDC': 125,
  'BNB/USDC:USDC': 75,
  'SOL/USDC:USDC': 100,
  'XRP/USDC:USDC': 75,
  'AI/USDT:USDT': 50,
  'XAI/USDT:USDT': 50,
  'DOGE/USDC:USDC': 75,
  'WIF/USDT:USDT': 50,
  'MANTA/USDT:USDT': 50,
  'ONDO/USDT:USDT': 50,
  'LSK/USDT:USDT': 50,
  'ALT/USDT:USDT': 50,
  'JUP/USDT:USDT': 50,
  'ZETA/USDT:USDT': 50,
  'RONIN/USDT:USDT': 50,
  'DYM/USDT:USDT': 50,
  'SUI/USDC:USDC': 50,
  'OM/USDT:USDT': 50,
  'LINK/USDC:USDC': 75,
  'PIXEL/USDT:USDT': 50,
  'STRK/USDT:USDT': 50,
  'MAVIA/USDT:USDT': 50,
  'ORDI/USDC:USDC': 75,
  'GLM/USDT:USDT': 50,
  'PORTAL/USDT:USDT': 50,
  'TON/USDT:USDT': 50,
  'AXL/USDT:USDT': 50,
  'MYRO/USDT:USDT': 50,
  '1000PEPE/USDC:USDC': 50,
  'METIS/USDT:USDT': 50,
  'AEVO/USDT:USDT': 50,
  'WLD/USDC:USDC': 75,
  'VANRY/USDT:USDT': 50,
  'BOME/USDT:USDT': 50,
  'ETHFI/USDT:USDT': 50,
  'AVAX/USDC:USDC': 75,
};
