name: Build Public Docker image

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: jtlab
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            "SITE_API_HOST=https://jt-lab.com"
          file: docker/Dockerfile
          push: true
          tags: jtlab/jtl-worker:${{ github.ref_name }}
